[env:esp32dev]
platform = espressif32
board = esp32s3
framework = arduino

monitor_speed = 115200

lib_deps =
    keyboard
    WiFi
    ESPAsyncWebServer

build_flags =
    -D DEBUG=1

[env:esp32s3]
platform = espressif32
board = esp32s3
framework = arduino

monitor_speed = 115200

lib_deps =
    keyboard
    WiFi
    ESPAsyncWebServer

build_flags =
    -D DEBUG=1