[env:teensy]
platform = teensy
board = teensy40
framework = arduino

[env:teensy40]
lib_deps =
    Keyboard
    USBHost
    Serial
build_flags = -DUSB_SERIAL
upload_port = /dev/ttyACM0
upload_protocol = teensy-cli
monitor_speed = 115200